### ISSUE TITLE
Grading code

### ISSUE THREAD

**Issue by julsas** [hl7germany/basisprofil-onkologie-R4#18]
https://github.com/hl7germany/basisprofil-onkologie-R4/blob/0e258f090c221db2aedaae220526fa013ec2f65e/input/fsh/observation.fsh#L146

https://loinc.org/59542-1/ scheint spezifisch zu sein für ein Grading System aus einem amerikanischen Register. Besser wäre https://loinc.org/33732-9/

**Comment by patrick-werner** [comment]
Danke für den Kommentar.
Nach meinem Verständnis wäre das ein Histologie spezifische Code. Ich glaube das ist auch nicht was wir wollen.

Ich habe noch: 21858-6 gefunden, ist zwar Bestandteil amerikanischer Panels, enthält aber keinen spezifischen Bezug auf AJCC Grading.
