### ISSUE TITLE
Wie Auflage von TNM erfassen?

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-onkologie-R4#19]
Vorschlag: Nutzung von versionierten TNM SIDs in Observation.method

**Comment by lhitc** [comment]
Warum nicht code.coding.version, wie bei anderen Codesystemen (ICD-10-GM, OPS, ...)?

**Comment by patrick-werner** [comment]
> Warum nicht code.coding.version, wie bei anderen Codesystemen (ICD-10-GM, OPS, ...)?

guter Vorschlag. Ich mache hier zu, und füge das gleich hinzu

**Comment by patrick-werner** [comment]
Weil code.coding system entweder Loinc oder SCT ist, also erfassen wir hier die Version von Loinc und SnomedCT

**Comment by lhitc** [comment]
Sorry, meinte valueCodeableConcept.coding.version.

Dort ist via entsprechendem Value Set das Codesystem gebunden, das aktuell unter der deutschen Canonical "http://fhir.de/onkologie/CodeSystem/UICCCS" läuft (sollte einen international einheitlichen Namen bekommen).
Dieses CS muss es nominal in Versionen äquivalent den UICC-TNM-Auflagen geben.
