### ISSUE TITLE
Create Observation profile Tumorstatus Fernmetastasen

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-onkologie-R4#5]

**Comment by patrick-werner** [comment]
ist dies nicht bereits im TNM Grading enthalten?

**Comment by alexzautke** [comment]
In STU3 hatten wir folgendes Profil dafür: https://simplifier.net/ccr/observation-cancer-base-tumorstatus-fernmetastasen-0.1-duplicate-2
