### ISSUE TITLE
Create Profile for Histopathologisches Grading

### ISSUE THREAD

**Issue by alexzautke** [hl7germany/basisprofil-onkologie-R4#8]

**Comment by patrick-werner** [comment]
G1 gut differenziert (hochdifferenzierter Tumor mit niederem Malignitätsgrad)
G2 mäßig differenziert (mittelhochdifferenzierter Tumor mit mittlerem Malignitätsgrad)
G3 schlecht / gering differenziert (wenig differenzierter Tumor mit hohem Malignitätsgrad)
G4 undifferenzierter Tumor mit sehr hohem Malignitätsgrad (nicht bei allen Tumorentitäten)
GX Differenzierungsgrad nicht bestimmbar
